# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwinsDiff < Formula
  desc "Web-based tool for comparing two directory trees"
  homepage "https://github.com/the-red/twins-diff"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.4/twins-diff_0.9.4_darwin_amd64.tar.gz"
      sha256 "295f52e31e3a0520735298c8afc43b925bda6a14f6aa7c870e8689f7c829efb7"

      define_method(:install) do
        bin.install "twins-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.4/twins-diff_0.9.4_darwin_arm64.tar.gz"
      sha256 "e266937c0fc66f1e7a021a167e22ed6c2f2edc8d45ef57e9bcce0906c1b9d901"

      define_method(:install) do
        bin.install "twins-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.4/twins-diff_0.9.4_linux_amd64.tar.gz"
      sha256 "025afc38e4f5f3767f8b3688ec317ef9a946cd2e79111a6a2f7bdf472d2244db"
      define_method(:install) do
        bin.install "twins-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.4/twins-diff_0.9.4_linux_arm64.tar.gz"
      sha256 "c6c99dcbf90f28fd1cebc1480bea848df16212ab3eae55c915f2e6a07cf7cac2"
      define_method(:install) do
        bin.install "twins-diff"
      end
    end
  end

  test do
    system "#{bin}/twins-diff", "-h"
  end
end
