# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwinsDiff < Formula
  desc "Web-based tool for comparing two directory trees"
  homepage "https://github.com/the-red/twins-diff"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.2/twins-diff_0.9.2_darwin_amd64.tar.gz"
      sha256 "23f8115b94d41d85adf32ce1a90a91ff02b0c645019e93915a6955857e3350b8"

      define_method(:install) do
        bin.install "twins-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.2/twins-diff_0.9.2_darwin_arm64.tar.gz"
      sha256 "0966d478bc9169ec1071a4096dedc2a73af66418eabe722960c80ea0880cbec6"

      define_method(:install) do
        bin.install "twins-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.2/twins-diff_0.9.2_linux_amd64.tar.gz"
      sha256 "deb32efd1d5eb962007b51c77af9efabe2893e1566941a8eed018ea0a8a802cf"
      define_method(:install) do
        bin.install "twins-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.2/twins-diff_0.9.2_linux_arm64.tar.gz"
      sha256 "d03248d62a106ece1f7bb6d8e41551c2806952080e7aab87eb03683d900f68a5"
      define_method(:install) do
        bin.install "twins-diff"
      end
    end
  end

  test do
    system "#{bin}/twins-diff", "-h"
  end
end
