# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TwinsDiff < Formula
  desc "Web-based tool for comparing two directory trees"
  homepage "https://github.com/the-red/twins-diff"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.0/twins-diff_0.9.0_darwin_amd64.tar.gz"
      sha256 "12121ca19ac8889780655acc203e6cd30110fa39cc1829b98f8fac905e43d537"

      define_method(:install) do
        bin.install "twins-diff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.0/twins-diff_0.9.0_darwin_arm64.tar.gz"
      sha256 "32ef413db86fd0886adf42978ff71ec2ebd61d9a39534e490f0c405accd8e518"

      define_method(:install) do
        bin.install "twins-diff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.0/twins-diff_0.9.0_linux_amd64.tar.gz"
      sha256 "59a141e677f361c277b6d6279009b8420103a17425141dc0ed5b138d28f32f65"
      define_method(:install) do
        bin.install "twins-diff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-red/twins-diff/releases/download/v0.9.0/twins-diff_0.9.0_linux_arm64.tar.gz"
      sha256 "04fb43e3e84dfbe916fe4121ddb3bf40fe903ef659ceed0aa7cf866ff93d0d13"
      define_method(:install) do
        bin.install "twins-diff"
      end
    end
  end

  test do
    system "#{bin}/twins-diff", "-h"
  end
end
